### ISSUE TITLE
Add ability to change base currency from USD

### ISSUE THREAD

**Issue by nickfarrow** [nickfarrow/SatSale#16]
Add a `config.py` option `base_currency = "USD"` that changes the price fetched by the API and also the display on the website.

Probably need
1) different price API which supports many currencies in [price_feed.py](https://github.com/nickfarrow/SatSale/blob/master/invoice/price_feed.py)
2) Write that `base_currency` string to `index.html` to overwrite the text. We probably don't need to parse this as an argument back through the API, simpler than overwriting the line in the HTML?

**Comment by ingolevin** [comment]
I have a first working draft here: https://github.com/ingolevin/SatSale/tree/16-change-base-currency

Note:
- Since `USD` is not longer the sole currency, I decided to rename the variables `dollar_value` --> `fiat_value` and `dollar_amount` --> `fiat_amount`. 
- HOWEVER: if you had your `database.db` created beforehands, this will be a **breaking change** because the column name in the `payments` table changed as well...   not sure whether that's permissible.
- Added a second price_feed (Coingecko). At the moment I have separate `get_coingecko|coindesk_price` functions... this can probably be made better

@nickfarrow I'm stuck with changing the "USD" in the index.html  - could use some help.

Instead of just a hardcoded string, there should rather be a dropdown where the user can pick the base_currency of the `amount` he's entering.

**Comment by nickfarrow** [comment]
This is fantastic, i'm just finishing off trying out `lightning addresses` then ill pull these changes and have a play around. Database break is fine by me, don't think it's a big deal and probably better to make this change sooner.

I'll fix up the HTML, im thinking we just display whatever currency `base_currency` is, with the intention of adding a toggle for sats(/btc) soon in the future. I'd be interested to hear your thoughts as to how easy it would be to make `base_currency = sats` an option too, could just be some trick with `get_btc_value`? Never actually doing any fiat conversion.

I feel like ive made a bit of a mess with all the currency conversions everywhere now, sorry about that, ill see if I can clear that up too. Thanks again

**Comment by ingolevin** [comment]
It still needs a bit of cleanup, then I will make a PR (without the HTML change). 
Remain todo:

1. I think we need to store the `base_currency` in the `payments` table, alongside the `fiat_value`
2. I want to have one common function `get_price(currency, price_feed_provider)`, instead of one for each feed_provider. The code is 90% identical; it should be possible to combine this on one function

Re: your questions:

- `base_currency` should be configurable, and in one place only, i.e. you set it in `config.py` and it _dynamically_ updates in the HTML.  I just suck at js/html, else I would have done it.
- The more I think about it, you probably need `base_currency` also as URL parameter. such the woo_commerce plugin can forward requests to SatSale that include a different currency than USD. Otherwise it can only support US Online shops

Toggle button "sats" | `base_currency` is fine.

**Comment by nickfarrow** [comment]
Yeah let's change the columns in the `payments` table. How about `base_currency` and `base_amount`? plus this would also make sense in the context of using BTC as the base currency.

A common get_price sounds like a good idea, having separate is ok too - wouldn't hurt to have two example `get_xxx_price(currency)` functions.

We can get the HTML to dynamically update by passing some `params={'base_currency':config.base_currency` when rendering index.html, like we do [here](https://github.com/nickfarrow/SatSale/blob/master/satsale.py#L62)

Not sure quite what the tag thing would be but something like {% params.base_currency %}. I can do when you're ready, or try yourself if you like

**Comment by ingolevin** [comment]
> We can get the HTML to dynamically update by passing some `params={'base_currency':config.base_currency` when rendering index.html, like we do [here](https://github.com/nickfarrow/SatSale/blob/master/satsale.py#L62)
> 
> Not sure quite what the tag thing would be but something like {% params.base_currency %}. I can do when you're ready, or try yourself if you like

Thanks for the hint - I shoudl be able to work that out. 

> Yeah let's change the columns in the payments table. How about base_currency and base_amount? plus this would also make sense in the context of using BTC as the base currency.

`base_currency` and `base_amount` sound good. 
That said, we may want to store additional data in the sqlite table in the future, and altering/dropping the table is not a viable upgrade path. I'll need to research this a bit more if it impacts sqlite performance, but I'd prefer to have the data jsoninfied and stored in one varchar(max) field `payment_data . You can parse the `payment_data`-json and decompose the fields in the `return` part of the `load_invoice`from_db` function. 
Will do some tests first, and a separate commit or even branch.

**Comment by nickfarrow** [comment]
Merged https://github.com/nickfarrow/SatSale/commit/58a55b8ed9fdd1d4b2ba949226d6d854cf058539
